### ISSUE TITLE
Force Match completion of Coproduct

### ISSUE THREAD

**Issue by juliusdeblaaij** [MewsSystems/FuncSharp#125]
Hello,
I was wondering about the following code:

```csharp
var spadesCard = new CardType(new Spades());

spadesCard.Match(
    spades => new Spades(),
    heart => new Heart(),
    clover => new Clover(),
    diamond => new Diamond()
);
```

Currently I matched all available CardTypes, but this code:

```csharp
var spadesCard = new CardType(new Spades());

spadesCard.Match(
    spades => new Spades(),
    heart => new Heart(),
    diamond => new Diamond()
);
```

Is equally valid for the compiler. This makes it, unlike F# not safe to use Match statements as something can just as easily slip through.
I know about _ matching every other option, but using _ should be a choice. Is there any way to write Match in such a way as togiven an error when not all types are matched (and no _ catchall is given)?
Thanks!

FIY: CardType is very basic:

```csharp
class CardType : Coproduct4<Spades, Clover, Heart, Diamond>
{
    public CardType(Spades spades) : base(spades)
    {
    }

    public CardType(Clover clover) : base(clover)
    {
    }

    public CardType(Heart heart) : base(heart)
    {
    }

    public CardType(Diamond diamond) : base(diamond)
    {
    }

    public CardType(ICoproduct4<Spades, Clover, Heart, Diamond> source) : base(source)
    {
    }

    protected CardType(int discriminator, object value) : base(discriminator, value)
    {
    }
}

class Spades : Product0
{
}

class Clover : Product0
{
}

class Heart : Product0
{
}

class Diamond : Product0
{
}
```

**Comment by KaliCZ** [comment]
Hey @juliusdeblaaij, 
there are 2 Match methods 
- one has params of `Func<CoproductValue, TResult>` and returns a `TResult`. This one enforces that all functions are provided.
- one has params of `Action<CoproductValue>` and is void. That's the one you're calling. And all the parameters are optional, so it is not enforced. 

The logic for why it is not enforced is that a lot of times you want to just write a conditional logic such as this
```
card.Match(
    ifThird: heart => Logger.Log("Hearts are the best!") 
);
```
And you wouldn't want to have to do this: 
```
card.Match(
    spades => { },
    heart => Logger.Log("Hearts are the best!"),
    clover => { },
    diamond => { }
);
```

Unfortunately, as Funcsharp is not native C# syntax, but juts generated C# methods, the `_ =>` cannot be used for matching the default case like you say. You will notice that the underscore is actually just a variable of one specific type based on the position of the lambda in your match. 

Is this explanation good enought for you? Would you be capable of converting your lambdas to return some value? Would that resolve your issue?

**Comment by juliusdeblaaij** [comment]
Hello, thank you very much for explaining both the rationale behind the Match statement as well as ```_```. I looked at calling the extension method that you mentioned, to enforce handling all cases. Unfortunately, I couldn't get a working sample even after looking at how it is implemented. Here's what I tried:

```csharp
// Cards.cs

using FuncSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PickCounter.Domain
{
    public class CardType : Product0
    {

    }

    class Card : Coproduct4<Spades, Clover, Heart, Diamond>
    {
        public Card(Spades spades) : base(spades)
        {
        }

        public Card(Clover clover) : base(clover)
        {
        }

        public Card(Heart heart) : base(heart)
        {
        }

        public Card(Diamond diamond) : base(diamond)
        {
        }

        public Card(ICoproduct4<Spades, Clover, Heart, Diamond> source) : base(source)
        {
        }

        protected Card(int discriminator, object value) : base(discriminator, value)
        {
        }
    }

    class Spades : CardType
    {
    }

    class Clover : CardType
    {
    }

    class Heart : CardType
    {
    }

    class Diamond : CardType
    {
    }
}
```

```csharp
// MauiProgram.cs

public static MauiApp CreateMauiApp()
{

// Builder code ...

var spadesCard = new Card(new Spades());

spadesCard.Match<CardType>(
    spades => HandleSpadesCard(spadesCard),
    clover => null,
    heart => null,
    diamond => null);

}

private static Card HandleSpadesCard(Card card)
{
    return null;
}
```

I get the following two errors:
- `CS1662	Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type`
- CS0029	Cannot implicitly convert type 'PickCounter.Domain.Card' to 'PickCounter.Domain.CardType'

I am very glad the Match<T> works and provides clear info when you miss a parameter!
If you could please provide a working alternative, perhaps relating to how I would implement i.e. a CoProduct of cards. That would really help with my understanding.

**Comment by KaliCZ** [comment]
@juliusdeblaaij Hey, that's just a simple mistake - the generics in the Match have to match the return type of the lambdas inside. So just by changing the return type of the method, it works.
![image](https://github.com/MewsSystems/FuncSharp/assets/12395130/57b3f6ca-ac91-41e6-be8c-bf478a6aefcd)

You don't actually have to specify the generic parameter when calling Match. But all the lambdas must have the same return type. So in your case, just doing this will work.
```
spadesCard.Match(
    spades => HandleSpadesCard(spadesCard),
    clover => null,
    heart => null,
    diamond => null
);
```

**Comment by juliusdeblaaij** [comment]
Thank you very much for clarifying. It is clear now, let's close this thread.
