### ISSUE TITLE
Improve documentation with code examples

### ISSUE THREAD

**Issue by KaliCZ** [MewsSystems/FuncSharp#77]
Noobs are having a hard time using funcsharp. A simple guide for how Options, ITries and Coproducts should be used would be super helpful. This guide would include code examples.

Come up with some high-level structure of documentation so that Code examples fit inside this structure.

**Comment by siroky** [comment]
@KaliCZ what do you think of making the examples directly part of the solution, so that you can even debug it if you would want to? And from the documentation, we would only linke the source files?

**Comment by siroky** [comment]
That way, the examples will also stay up-to date as they'll have to pass build.

**Comment by KaliCZ** [comment]
Sure, makes sense :)

**Comment by siroky** [comment]
Prepared the structure, documented algebraic data types, similar structure can be used for other types:
- Short description in readme
- Short code example in readme
- More examples, usages etc. in the project, linked from readme.

Check how e.g. coproduct is done and if you have some additions, please try to follow this pattern. I want the readme to be rather short and succinct, more elaborate examples and showcase of all possible methods and use-cases can be in the examples project.
